version: 1.0.{build}
os:
  - Visual Studio 2015
clone_depth: 1
configuration:
  - Debug
platform:
  - Win32
  - x64
environment:
  OPENSSL_INCLUDE_DIR: C:\OpenSSL\include
  OPENSSL_LIB_DIR: C:\OpenSSL\lib
  OPENSSL_LIBS: ssleay32:libeay32

  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.7.0

build_script: mk/appveyor.bat
